name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag nirjas:latest

    - name: Upload image
      uses: ishworkh/docker-image-artifact-upload@v1
      with:
        image: "nirjas:latest"
